version: '3.9'

services:
  simple-web-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    volumes:
      - /home/node/app/node_modules
    restart: always
    environment:
      - NODE_ENV=prod
      - PORT=80
